language: python

matrix:
    include:
        - os: linux
          python: 3.5

install:
    - pip install flake8 pylint

script:
    - flake8 pywal tests setup.py
    - pylint pywal tests setup.py
